window.GameState = {
  app: null,
  stage: null,
  bgLayer: null,
  world: null,
  bg: null,
  fx: null,
  uiLayer: null,
  bgGfx: null,
  bgDecor: null,

  mouse: { x:0, y:0, down:false },
  keys: new Set(),

  player: null,
  decoys: [],
  smokeClouds: [],
  slowFields: [],
  hazards: [],
  planets: [],
  mines: [],
  bullets: [],
  enemyBullets: [],
  beams: [],
  missiles: [],
  enemies: [],
  particles: [],
  textureCache: {},
  hazardTimer: 360,
  playerType: "standard",
  practiceBossId: "basic",
  practiceStageId: 1,
  practiceStageDurationSec: 180,
  practiceEnemyTier: "normal",
  practiceEnemyCount: 3,
  difficulty: "normal",
  effectQuality: "standard",
  autoFire: true,
  autoAim: false,
  movementMode: "keyboard",
  camera: {
    x: 0,
    y: 0
  },
  arena: {
    left: 0,
    top: 0,
    width: 0,
    height: 0
  },

  stats: {
    maxHp: 100,
    hp: 100,
    speed: GAME_BALANCE.PLAYER.MOVE_SPEED,
    dashSpeed: GAME_BALANCE.PLAYER.DASH_SPEED,
    dashCd: 0,
    dashCdMax: GAME_BALANCE.PLAYER.DASH_CD_MAX,
    fireRate: GAME_BALANCE.PLAYER.FIRE_RATE_BASE,
    bulletSpeed: GAME_BALANCE.PLAYER.BULLET_SPEED,
    bulletDamage: GAME_BALANCE.PLAYER.BULLET_DAMAGE,
    bulletCount: GAME_BALANCE.PLAYER.BULLET_COUNT,
    weaponLevel: 1,
    bulletPierce: 0,
    rangeMultiplier: 1,
    hardpointLevel: 0,
    hardpointCooldown: 0,
    escortDroneLevel: 0,
    defense: GAME_BALANCE.PLAYER.DEFENSE,
    mp: GAME_BALANCE.PLAYER.MP_MAX,
    mpMax: GAME_BALANCE.PLAYER.MP_MAX,
    mpRegen: GAME_BALANCE.PLAYER.MP_REGEN,
    regen: 0,
    shield: 0,
    shieldMax: 0,
    shieldRegen: 0,
    shieldRegenDelay: 0,
    shieldRegenDelayMax: GAME_BALANCE.PLAYER.SHIELD_REGEN_DELAY_MAX,
    homingMissileLevel: 0,
    homingMissileDamage: GAME_BALANCE.PLAYER.HOMING_MISSILE_DAMAGE,
    homingMissileCd: 0,
    homingMissileCdMax: GAME_BALANCE.PLAYER.HOMING_MISSILE_CD_MAX,
    flakLevel: 0,
    flakCooldown: 0,
    arcLevel: 0,
    arcCooldown: 0,
    mineLevel: 0,
    mineCd: 0,
    mineCdMax: 0,
    mineMaxCount: 0,
    mineRadius: 0,
    mineDamage: 0,
    chainAttackLevel: 0,
    slowFieldLevel: 0,
    slowFieldCooldown: 0,
    practice: false,
    practiceMode: "none"
  },

  progression: {
    score: 0,
    combo: 1,
    comboT: 0,
    stage: 1,
    stageTime: 180 * 60,
    stageDuration: 180 * 60,
    stageState: "combat",
    wave: 1,
    waveAlive: 0,
    waveTarget: 8,
    waveState: "idle",
    spawnT: 0,
    spawnedCount: 0,
    level: 1,
    xp: 0,
    xpToNext: GAME_BALANCE.XP.BASE_TO_NEXT,
    pendingLevelUps: 0,
    levelUpRerollUsed: false,
    bossFinishTimer: 0,
    deathTimer: 0
  },

  upgrades: {
    levels: {},
    pickedIds: [],
    categoryCounts: {
      weapon: 0,
      passive: 0,
      active: 0
    }
  },

  activeSkillState: {
    slots: [
      { key:"KeyQ", label:"Q", skillId:null, cooldown:0, autoCast:false },
      { key:"KeyE", label:"E", skillId:null, cooldown:0, autoCast:false },
      { key:"KeyR", label:"R", skillId:null, cooldown:0, autoCast:false }
    ],
    ownedSkillIds: [],
    levels: {
      boost: 1
    },
    boostDirection: "forward",
    boostDir: 0,
    boostDrag: 0.9,
    boostMitigationT: 0,
    boostMitigationMul: 1,
    boostT: 0,
    afterburnerT: 0,
    escortDrones: [],
    deployTurrets: [],
    swarmDrones: [],
    trapPrisms: [],
    novaPulses: [],
    repulsorFields: [],
    stasisArcFields: [],
    recallBoostT: 0,
    recallFireRateMul: 1,
    recallDamageMul: 1,
    stealthT: 0,
    stealthAlpha: 1,
    stealthLastKnownX: 0,
    stealthLastKnownY: 0
  },

  weaponState: {
    current: "machinegun",
    laserChannel: null
  },

  pause: {
    open: false
  },

  shake: 0
};
